image: docker:latest

stages:
  - deploy 

deploy_staging:
  stage: deploy
  script:
    - export DOCKER_TLS_VERIFY="1"
    - export DOCKER_HOST="tcp://192.168.99.103:2376"
    - export DOCKER_CERT_PATH="/.docker/machine/machines/manager1"
    - export DOCKER_MACHINE_NAME="manager1"
    - docker stack deploy --compose-file docker-stack.yml vote

  environment:
    name: staging
    url: http://192.168.99.103:5000
  only:
  - master

deploy_review:
  stage: deploy
  script:
    - export DOCKER_TLS_VERIFY="1"
    - export DOCKER_HOST="tcp://192.168.99.103:2376"
    - export DOCKER_CERT_PATH="/.docker/machine/machines/manager1"
    - export DOCKER_MACHINE_NAME="manager1"
    - docker stack deploy --compose-file docker-stack.yml $CI_ENVIRONMENT_SLUG
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG_vote.machine.local
  only:
    - branches
  except:
    - master