image: docker:latest

stages:
  - test
  - deploy 
  
test:
  stage: test
  script:
    - ls -alrth /my-app

# deploy_staging:
#   stage: deploy
#   script:
#     - export DOCKER_TLS_VERIFY="1"
#     - export DOCKER_HOST="tcp://192.168.99.103:2376"
#     - export DOCKER_CERT_PATH="/.docker/machine/machines/manager1"
#     - export DOCKER_MACHINE_NAME="manager1"

#   environment:
#     name: staging
#     url: https://192.168.99.103:5000
#   only:
#   - master